### ISSUE TITLE
UT] Call unsuccessful after 4 tries. Retrying in 8 seconds...

### ISSUE THREAD

**Issue by A-bhiSheKumar** [AntonioErdeljac/next13-lms-platform#12]
While uploading a image through uplodthing

**Comment by A-bhiSheKumar** [comment]
Solved mySelf

**Comment by jeffclaybrook** [comment]
@A-bhiSheKumar I'm having this issue right now. Any chance you could share your solution?

**Comment by A-bhiSheKumar** [comment]
@jeffclaybrook Sorry, I have seen this too late it's a small error that we are having inside our middleware.tsx file...>

import { authMiddleware } from "@clerk/nextjs";

 export default authMiddleware({ 
  publicRoutes:["/api/uploadthing"]
});
 
export const config = {
  matcher: ['/((?!.+\\.[\\w]+$|_next).*)', '/', '/(api|trpc)(.*)'],

};


Just update your middleware.tsx file you need to change that Webhook to uploadthing .


Let's connect on twitter:--> https://twitter.com/Stack_Abhi
